simplify code for getting presentation anchor
paypal/paypal-ios pull request #103
Opened 2022-12-15 22:27 UTC by kgangineni

### Reason for changes

1. Simplify code snippet for retrieving presentation anchor
2. couldn't fix runtime warning of running on background thread

### Summary of changes

- 

### Checklist

- [ ] Added a changelog entry

### Authors
> List GitHub usernames for everyone who contributed to this pull request.

- @kgangineni @scannillo

2022-12-16 15:05 UTC, jaxdesmarais commented
> couldn't fix runtime warning of running on background thread

Looks like we have 2 options to resolve this. We can either add `@MainActor` to `startThreeDSecureChallenge`:
```
    @MainActor
    private func startThreeDSecureChallenge(
        url: String,
        orderId: String,
        context: ASWebAuthenticationPresentationContextProviding,
        webAuthenticationSession: WebAuthenticationSession
    ) {
```

Then add `await` to when you call this in the `CardClient.start` function.

Alternatively, you call `startThreeDSecureChallenge` from the main thread in the `CardClient.start` function:
```
DispatchQueue.main.async {
    self.startThreeDSecureChallenge(url: url, orderId: result.id, context: context, webAuthenticationSession: webAuthenticationSession)
}
```
Both options should resolve the main thread warnings. 😄

2022-12-16 15:07 UTC, jaxdesmarais requested changes

2022-12-16 15:07 UTC, jaxdesmarais commented on Demo/Demo/FeatureViewControllers/FeatureBaseViewController.swift
> +        return window ?? ASPresentationAnchor()
Nice! This is certainly a lot cleaner. Left a comment on how we can also resolve the main thread warning!

2023-01-11 16:46 UTC, scannillo commented
Closing this PR in favor of https://github.com/paypal/iOS-SDK/pull/104

2023-01-11 16:46 UTC, closed without merging